export const restaurants = [
    {
        info: {
            id: "23945",
            name: "Domino's Pizza",
            cloudinaryImageId: "rde17nnu9xcpevuynr6y",
            locality: "AJC Bose Road",
            areaName: "Taltala",
            costForTwo: "₹400 for two",
            cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
            avgRating: 4.4,
            parentId: "2456",
            avgRatingString: "4.4",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 28,
                lastMileTravel: 2.1,
                serviceability: "SERVICEABLE",
                slaString: "28 mins",
                lastMileTravelString: "2.1 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 02:57:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "₹150 OFF",
                subHeader: "ABOVE ₹299",
                discountTag: "FLAT DEAL",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/dominos-pizza-ajc-bose-road-taltala-kolkata-23945",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "39236",
            name: "KFC",
            cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
            locality: "Central",
            areaName: "Park Street Area",
            costForTwo: "₹450 for two",
            cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
            avgRating: 4.3,
            parentId: "547",
            avgRatingString: "4.3",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 32,
                lastMileTravel: 3,
                serviceability: "SERVICEABLE",
                slaString: "32 mins",
                lastMileTravelString: "3.0 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 02:59:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/kfc-central-park-street-area-kolkata-39236",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "149283",
            name: "Pizza Hut",
            cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
            locality: "FCD Park Street Kolkata",
            areaName: "Park Street Area",
            costForTwo: "₹350 for two",
            cuisines: ["Fast Food", "Pizzas"],
            avgRating: 4.2,
            parentId: "721",
            avgRatingString: "4.2",
            totalRatingsString: "5K+",
            sla: {
                deliveryTime: 35,
                lastMileTravel: 3,
                serviceability: "SERVICEABLE",
                slaString: "35 mins",
                lastMileTravelString: "3.0 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 01:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/pizza-hut-fcd-park-street-park-street-area-kolkata-149283",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "407662",
            name: "Burger King",
            cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
            locality: "New Market",
            areaName: "Esplanade",
            costForTwo: "₹350 for two",
            cuisines: ["Burgers", "American"],
            avgRating: 4.2,
            parentId: "166",
            avgRatingString: "4.2",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 33,
                lastMileTravel: 2.8,
                serviceability: "SERVICEABLE",
                slaString: "33 mins",
                lastMileTravelString: "2.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 06:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/burger-king-new-market-esplanade-kolkata-407661",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "326959",
            name: "6 Ballygunge Place",
            cloudinaryImageId: "fh8lmt0d5cnx8fgj5bpk",
            locality:
                "Near Rajabazar Science College, Vidyasagar Street, between HP Petrol Pump and Canis Care Pet",
            areaName: "Machuabazar",
            costForTwo: "₹800 for two",
            cuisines: ["Bengali"],
            avgRating: 4.5,
            parentId: "1243",
            avgRatingString: "4.5",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 24,
                lastMileTravel: 1.7,
                serviceability: "SERVICEABLE",
                slaString: "24 mins",
                lastMileTravelString: "1.7 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 00:00:00",
                opened: true,
            },
            badges: {
                imageBadges: [
                    {
                        imageId: "newg.png",
                        description: "Gourmet",
                    },
                ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: "Gourmet",
                                    imageId: "newg.png",
                                },
                            },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/6-ballygunge-place-near-rajabazar-science-college-vidyasagar-street-between-hp-petrol-pump-and-canis-care-pet-machuabazar-kolkata-326959",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "37107",
            name: "Natural Ice Cream",
            cloudinaryImageId: "ow0tfhk3nw7ag7telsy1",
            locality: "Park Street",
            areaName: "Taltala",
            costForTwo: "₹150 for two",
            cuisines: ["Ice Cream", "Desserts"],
            avgRating: 4.7,
            parentId: "2093",
            avgRatingString: "4.7",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 24,
                lastMileTravel: 2.8,
                serviceability: "SERVICEABLE",
                slaString: "24 mins",
                lastMileTravelString: "2.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 00:45:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                discountTag: "FLAT DEAL",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/natural-ice-cream-park-street-taltala-kolkata-37107",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "213121",
            name: "Wow! Momo",
            cloudinaryImageId: "0984acc0ed7b914206dbbcb90297becc",
            locality: "Sealdah Railway Station",
            areaName: "Burrabazar",
            costForTwo: "₹200 for two",
            cuisines: [
                "Tibetan",
                "Chinese",
                "Snacks",
                "Continental",
                "Desserts",
            ],
            avgRating: 4.3,
            parentId: "1776",
            avgRatingString: "4.3",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 27,
                lastMileTravel: 1.7,
                serviceability: "SERVICEABLE",
                slaString: "27 mins",
                lastMileTravelString: "1.7 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:59:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "ITEMS",
                subHeader: "AT ₹99",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/wow-momo-sealdah-railway-station-burrabazar-kolkata-213121",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "324200",
            name: "Faasos - Wraps, Rolls & Shawarma",
            cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
            locality: "DR SURESH CHANDRA BANERJEE ROAD",
            areaName: "Beleghata",
            costForTwo: "₹200 for two",
            cuisines: [
                "Kebabs",
                "Fast Food",
                "Snacks",
                "American",
                "Healthy Food",
                "Desserts",
                "Beverages",
            ],
            avgRating: 4.3,
            parentId: "21809",
            avgRatingString: "4.3",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 33,
                lastMileTravel: 4.8,
                serviceability: "SERVICEABLE",
                slaString: "33 mins",
                lastMileTravelString: "4.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:59:00",
                opened: true,
            },
            badges: {
                textExtendedBadges: [
                    {
                        iconId: "guiltfree/GF_Logo_android_3x",
                        shortDescription: "options available",
                        fontColor: "#7E808C",
                    },
                ],
            },
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: "",
                                    fontColor: "#7E808C",
                                    iconId: "guiltfree/GF_Logo_android_3x",
                                    shortDescription: "options available",
                                },
                            },
                        ],
                    },
                },
            },
            aggregatedDiscountInfoV3: {
                header: "ITEMS",
                subHeader: "AT ₹129",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/faasos-wraps-rolls-and-shawarma-dr-suresh-chandra-banerjee-road-beleghata-kolkata-324200",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "324201",
            name: "Behrouz Biryani",
            cloudinaryImageId: "89fccaa76f2f760e2742b9e53d32bb69",
            locality: "DR SURESH CHANDRA BANERJEE ROAD",
            areaName: "Beleghata",
            costForTwo: "₹500 for two",
            cuisines: [
                "Biryani",
                "North Indian",
                "Kebabs",
                "Mughlai",
                "Lucknowi",
                "Hyderabadi",
                "Desserts",
                "Beverages",
            ],
            avgRating: 4.4,
            parentId: "1803",
            avgRatingString: "4.4",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 32,
                lastMileTravel: 4.8,
                serviceability: "SERVICEABLE",
                slaString: "32 mins",
                lastMileTravelString: "4.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:59:00",
                opened: true,
            },
            badges: {
                imageBadges: [
                    {
                        imageId: "newg.png",
                        description: "Gourmet",
                    },
                ],
            },
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: "Gourmet",
                                    imageId: "newg.png",
                                },
                            },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹110",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/behrouz-biryani-dr-suresh-chandra-banerjee-road-beleghata-kolkata-324201",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "324202",
            name: "Oven Story Pizza - Standout Toppings",
            cloudinaryImageId: "ab979bffbd658e74de650a15ca0092a3",
            locality: "DR SURESH CHANDRA BANERJEE ROAD",
            areaName: "Beleghata",
            costForTwo: "₹400 for two",
            cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
            avgRating: 4.3,
            parentId: "3534",
            avgRatingString: "4.3",
            totalRatingsString: "5K+",
            sla: {
                deliveryTime: 35,
                lastMileTravel: 4.8,
                serviceability: "SERVICEABLE",
                slaString: "35 mins",
                lastMileTravelString: "4.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:59:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹110",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/oven-story-pizza-standout-toppings-dr-suresh-chandra-banerjee-road-beleghata-kolkata-324202",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "48895",
            name: "The Belgian Waffle Co.",
            cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
            locality: "CIT Road Scheme VI",
            areaName: "Kankurgachi",
            costForTwo: "₹200 for two",
            cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
            avgRating: 4.6,
            veg: true,
            parentId: "2233",
            avgRatingString: "4.6",
            totalRatingsString: "5K+",
            sla: {
                deliveryTime: 35,
                lastMileTravel: 4.3,
                serviceability: "SERVICEABLE",
                slaString: "35 mins",
                lastMileTravelString: "4.3 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:30:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/the-belgian-waffle-co-cit-road-scheme-vi-kankurgachi-kolkata-48895",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "4430",
            name: "Shiraz Golden Restaurant",
            cloudinaryImageId: "hsks21k01bgfajnv89fr",
            locality: "Park Circus",
            areaName: "Park Circus",
            costForTwo: "₹500 for two",
            cuisines: [
                "Biryani",
                "Mughlai",
                "North Indian",
                "Indian",
                "Kebabs",
                "Tandoor",
            ],
            avgRating: 4.5,
            parentId: "5569",
            avgRatingString: "4.5",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 34,
                lastMileTravel: 3.7,
                serviceability: "SERVICEABLE",
                slaString: "34 mins",
                lastMileTravelString: "3.7 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:25:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/shiraz-golden-restaurant-park-circus-kolkata-4430",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "67717",
            name: "Kookie Jar",
            cloudinaryImageId: "0b69d733f3174c1d7ef9829e2a2fc33b",
            locality: "Rowdon Street",
            areaName: "Loudon Street",
            costForTwo: "₹350 for two",
            cuisines: ["Desserts", "Snacks", "Bakery", "Ice Cream"],
            avgRating: 4.7,
            parentId: "5550",
            avgRatingString: "4.7",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 31,
                lastMileTravel: 3.8,
                serviceability: "SERVICEABLE",
                slaString: "31 mins",
                lastMileTravelString: "3.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 22:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/kookie-jar-rowdon-street-loudon-street-kolkata-67717",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "18107",
            name: "Bhojohori Manna",
            cloudinaryImageId: "17d6b518e586e760d9ca4ad0de775d9e",
            locality: "Esplanade",
            areaName: "Bentinck St.",
            costForTwo: "₹900 for two",
            cuisines: ["Bengali", "Biryani"],
            avgRating: 4,
            parentId: "113",
            avgRatingString: "4.0",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 30,
                lastMileTravel: 1.8,
                serviceability: "SERVICEABLE",
                slaString: "30 mins",
                lastMileTravelString: "1.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 22:30:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "10% OFF",
                subHeader: "UPTO ₹40",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/bhojohori-manna-esplanade-bentinck-st-kolkata-18107",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "19521",
            name: "Tea Junction",
            cloudinaryImageId: "77d2fffe27cd59af5045a102d08af522",
            locality: "Lindsay Street",
            areaName: "New Market Area",
            costForTwo: "₹150 for two",
            cuisines: ["Beverages", "Snacks", "Desserts"],
            avgRating: 4.4,
            parentId: "4311",
            avgRatingString: "4.4",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 29,
                lastMileTravel: 2.5,
                serviceability: "SERVICEABLE",
                slaString: "29 mins",
                lastMileTravelString: "2.5 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 21:45:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/tea-junction-lindsay-street-new-market-area-kolkata-19521",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "285433",
            name: "Kathleen",
            cloudinaryImageId: "e40c5b9a0187a3666d7936275ebf020a",
            locality: "Burrabazar",
            areaName: "Bentick St",
            costForTwo: "₹200 for two",
            cuisines: ["Desserts", "Bakery", "Snacks", "Continental"],
            avgRating: 4.4,
            parentId: "10674",
            avgRatingString: "4.4",
            totalRatingsString: "100+",
            sla: {
                deliveryTime: 24,
                lastMileTravel: 1.7,
                serviceability: "SERVICEABLE",
                slaString: "24 mins",
                lastMileTravelString: "1.7 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 21:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "10% OFF",
                subHeader: "UPTO ₹40",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/kathleen-burrabazar-bentick-st-kolkata-285433",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "94773",
            name: "Gupta Brothers",
            cloudinaryImageId: "jo5dqjsbg1k1o1giaf82",
            locality: "Chandni Chowk",
            areaName: "Bentinck St.",
            costForTwo: "₹100 for two",
            cuisines: ["Indian", "Chinese", "Italian", "Sweets"],
            avgRating: 4.3,
            veg: true,
            parentId: "437",
            avgRatingString: "4.3",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 27,
                lastMileTravel: 1.4,
                serviceability: "SERVICEABLE",
                slaString: "27 mins",
                lastMileTravelString: "1.4 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 20:00:00",
                opened: true,
            },
            badges: {
                imageBadges: [
                    {
                        imageId: "v1695133679/badges/Pure_Veg111.png",
                        description: "pureveg",
                    },
                ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: "pureveg",
                                    imageId:
                                        "v1695133679/badges/Pure_Veg111.png",
                                },
                            },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/gupta-brothers-chandni-chowk-bentinck-st-kolkata-94773",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "58090",
            name: "Cakes",
            cloudinaryImageId: "qlpywzh0rp3zc7n1qngc",
            locality: "Beside Ghosh Brothers Sweet",
            areaName: "Beleghata",
            costForTwo: "₹200 for two",
            cuisines: ["Bakery", "Desserts"],
            avgRating: 4.6,
            parentId: "4861",
            avgRatingString: "4.6",
            totalRatingsString: "5K+",
            sla: {
                deliveryTime: 25,
                lastMileTravel: 3.5,
                serviceability: "SERVICEABLE",
                slaString: "25 mins",
                lastMileTravelString: "3.5 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 20:30:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/cakes-beside-ghosh-brothers-sweet-beleghata-kolkata-58090",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "55192",
            name: "Kareem's",
            cloudinaryImageId: "zmwfgkadrc6gxyfnai1e",
            locality: "Near Hotel Heera International",
            areaName: "Taltala",
            costForTwo: "₹1100 for two",
            cuisines: ["Biryani", "North Indian", "Mughlai"],
            avgRating: 4.3,
            parentId: "534",
            avgRatingString: "4.3",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 35,
                lastMileTravel: 2.6,
                serviceability: "SERVICEABLE",
                slaString: "35 mins",
                lastMileTravelString: "2.6 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 00:00:00",
                opened: true,
            },
            badges: {
                imageBadges: [
                    {
                        imageId: "newg.png",
                        description: "Gourmet",
                    },
                ],
            },
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: "Gourmet",
                                    imageId: "newg.png",
                                },
                            },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/kareems-near-hotel-heera-international-taltala-kolkata-55192",
            type: "WEBLINK",
        },
    },
    {
        info: {
            id: "25140",
            name: "Zam Zam Restaurant",
            cloudinaryImageId: "e85899aceae5ebe729d0440e4b1239df",
            locality: "Entally",
            areaName: "Central Kolkata",
            costForTwo: "₹200 for two",
            cuisines: ["Mughlai", "Biryani"],
            avgRating: 4.4,
            parentId: "8883",
            avgRatingString: "4.4",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 28,
                lastMileTravel: 2.9,
                serviceability: "SERVICEABLE",
                slaString: "28 mins",
                lastMileTravelString: "2.9 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 02:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: "https://www.swiggy.com/restaurants/zam-zam-restaurant-entally-central-kolkata-kolkata-25140",
            type: "WEBLINK",
        },
    },

    {
        info: {
            id: "8693",
            name: "New Paul Dhaba - Veggie Hub",
            cloudinaryImageId: "wmlntcabugrcpwx12j1p",
            locality: "Maniktala",
            areaName: "Kolkata",
            costForTwo: "₹250 for two",
            cuisines: ["North Indian", "Chinese", "South Indian", "Tandoor"],
            avgRating: 4.3,
            veg: true,
            parentId: "1651",
            avgRatingString: "4.3",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 27,
                lastMileTravel: 2,
                serviceability: "SERVICEABLE",
                slaString: "27 mins",
                lastMileTravelString: "2.0 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:00:00",
                opened: true,
            },
            badges: {
                imageBadges: [
                    {
                        imageId: "v1695133679/badges/Pure_Veg111.png",
                        description: "pureveg",
                    },
                ],
            },
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: "pureveg",
                                    imageId:
                                        "v1695133679/badges/Pure_Veg111.png",
                                },
                            },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/new-paul-dhaba-veggie-hub-maniktala-kolkata-kolkata-8693",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "642333",
            name: "Wah Janaab",
            cloudinaryImageId: "zyj8ksdsb2dixjutecna",
            locality: "Mirza Galib Street",
            areaName: "Central Kolkata",
            costForTwo: "₹200 for two",
            cuisines: ["Burgers", "Beverages"],
            avgRating: 4.3,
            parentId: "259030",
            avgRatingString: "4.3",
            totalRatingsString: "500+",
            sla: {
                deliveryTime: 32,
                lastMileTravel: 2.4,
                serviceability: "SERVICEABLE",
                slaString: "32 mins",
                lastMileTravelString: "2.4 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:59:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/wah-janaab-mirza-galib-street-central-kolkata-kolkata-642333",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "8822",
            name: "Amber-Esplanade",
            cloudinaryImageId: "fkfucctjuylaarok0v4m",
            locality: "Esplanade",
            areaName: "Esplanade",
            costForTwo: "₹700 for two",
            cuisines: ["North Indian", "Continental"],
            avgRating: 4.4,
            parentId: "31217",
            avgRatingString: "4.4",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 34,
                lastMileTravel: 1.8,
                serviceability: "SERVICEABLE",
                slaString: "34 mins",
                lastMileTravelString: "1.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 22:15:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/amber-esplanade-esplanade-kolkata-8822",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "199142",
            name: "Acs Chinese Flavour",
            cloudinaryImageId: "bdxngpdzohlfvsnrfkmr",
            locality: "Taltala",
            areaName: "Taltala",
            costForTwo: "₹300 for two",
            cuisines: ["Chinese"],
            avgRating: 4.1,
            parentId: "26894",
            avgRatingString: "4.1",
            totalRatingsString: "5K+",
            sla: {
                deliveryTime: 27,
                lastMileTravel: 2.5,
                serviceability: "SERVICEABLE",
                slaString: "27 mins",
                lastMileTravelString: "2.5 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "30% OFF",
                subHeader: "UPTO ₹75",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/acs-chinese-flavour-taltala-kolkata-199142",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "101421",
            name: "Mughal Shahi Biryani",
            cloudinaryImageId: "dqryaxhlba4okzyzcx5z",
            locality: "MG road",
            areaName: "College Square",
            costForTwo: "₹200 for two",
            cuisines: ["Indian", "Biryani"],
            avgRating: 4.1,
            parentId: "471260",
            avgRatingString: "4.1",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 20,
                lastMileTravel: 1.3,
                serviceability: "SERVICEABLE",
                slaString: "20 mins",
                lastMileTravelString: "1.3 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 00:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/mughal-shahi-biryani-mg-road-college-square-kolkata-101421",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "278225",
            name: "AL Baik Fast Food Center",
            cloudinaryImageId: "k3vuj7cncnfbwqqfkpbc",
            locality: "Burrabazar",
            areaName: "Barabazar Market",
            costForTwo: "₹300 for two",
            cuisines: ["Biryani", "Snacks", "North Indian"],
            avgRating: 3.9,
            parentId: "28935",
            avgRatingString: "3.9",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 25,
                lastMileTravel: 0.9,
                serviceability: "SERVICEABLE",
                slaString: "25 mins",
                lastMileTravelString: "0.9 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:59:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/al-baik-fast-food-center-burrabazar-barabazar-market-kolkata-278225",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "407661",
            name: "Burger King",
            cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
            locality: "New Market",
            areaName: "Esplanade",
            costForTwo: "₹350 for two",
            cuisines: ["Burgers", "American"],
            avgRating: 4.2,
            parentId: "166",
            avgRatingString: "4.2",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 33,
                lastMileTravel: 2.8,
                serviceability: "SERVICEABLE",
                slaString: "33 mins",
                lastMileTravelString: "2.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 06:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/burger-king-new-market-esplanade-kolkata-407661",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "202889",
            name: "Tung Fong",
            cloudinaryImageId: "mybmqrfdpakmwd7fda5t",
            locality: "Park Street Area",
            areaName: "Park Street Area",
            costForTwo: "₹1200 for two",
            cuisines: ["Asian", "Chinese"],
            avgRating: 4.6,
            parentId: "218448",
            avgRatingString: "4.6",
            totalRatingsString: "5K+",
            sla: {
                deliveryTime: 36,
                lastMileTravel: 3,
                serviceability: "SERVICEABLE",
                slaString: "36 mins",
                lastMileTravelString: "3.0 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 22:45:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "₹200 OFF",
                subHeader: "ABOVE ₹1400",
                discountTag: "FLAT DEAL",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/tung-fong-park-street-area-kolkata-202889",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "18359",
            name: "Apu's Kitchen Phool Bagan",
            cloudinaryImageId: "e49fwbcb7szcnnj44sht",
            locality: "Hem Chandra Naskar Road",
            areaName: "NearGurudasPark",
            costForTwo: "₹250 for two",
            cuisines: [
                "Chinese",
                "North Indian",
                "Mughlai",
                "Biryani",
                "Kebabs",
            ],
            avgRating: 4.4,
            parentId: "6113",
            avgRatingString: "4.4",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 28,
                lastMileTravel: 3.5,
                serviceability: "SERVICEABLE",
                slaString: "28 mins",
                lastMileTravelString: "3.5 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:59:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "₹100 OFF",
                subHeader: "ABOVE ₹199",
                discountTag: "FLAT DEAL",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/apus-kitchen-phool-bagan-hem-chandra-naskar-road-neargurudaspark-kolkata-18359",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "703276",
            name: "Idlygo Plus",
            cloudinaryImageId: "f2f4cf1bb6e27157a2b240694ba95c9d",
            locality: "Vivekananda road",
            areaName: "Burrabazar",
            costForTwo: "₹150 for two",
            cuisines: ["South Indian", "Snacks"],
            avgRating: 4.3,
            veg: true,
            parentId: "428184",
            avgRatingString: "4.3",
            totalRatingsString: "100+",
            sla: {
                deliveryTime: 29,
                lastMileTravel: 2.2,
                serviceability: "SERVICEABLE",
                slaString: "29 mins",
                lastMileTravelString: "2.2 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 22:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/idlygo-plus-vivekananda-road-burrabazar-kolkata-703276",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "156690",
            name: "Rayyan Biryani",
            cloudinaryImageId: "dlkugxln3bpvr3jouumx",
            locality: "Esplanade",
            areaName: "Taltala",
            costForTwo: "₹200 for two",
            cuisines: ["Biryani", "Mughlai"],
            avgRating: 3.5,
            parentId: "18596",
            avgRatingString: "3.5",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 26,
                lastMileTravel: 2.5,
                serviceability: "SERVICEABLE",
                slaString: "26 mins",
                lastMileTravelString: "2.5 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 23:59:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹95",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/rayyan-biryani-esplanade-taltala-kolkata-156690",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "616808",
            name: "Momo Wala",
            cloudinaryImageId: "6001cbfdc886eb75d2ff7aeafab0cf37",
            areaName: "Central Kolkata",
            costForTwo: "₹300 for two",
            cuisines: ["Chinese", "Tibetan"],
            avgRating: 4.2,
            parentId: "471848",
            avgRatingString: "4.2",
            totalRatingsString: "100+",
            sla: {
                deliveryTime: 31,
                lastMileTravel: 1.8,
                serviceability: "SERVICEABLE",
                slaString: "31 mins",
                lastMileTravelString: "1.8 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-28 00:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "30% OFF",
                subHeader: "UPTO ₹75",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/momo-wala-central-kolkata-kolkata-616808",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "31623",
            name: "Bombay Shiv Sagar",
            cloudinaryImageId: "vatangfaebhbwxzhnhyr",
            locality: "Camac Street",
            areaName: "Camac Street",
            costForTwo: "₹500 for two",
            cuisines: ["North Indian", "South Indian", "Chinese"],
            avgRating: 4.4,
            parentId: "48847",
            avgRatingString: "4.4",
            totalRatingsString: "10K+",
            sla: {
                deliveryTime: 35,
                lastMileTravel: 3,
                serviceability: "SERVICEABLE",
                slaString: "35 mins",
                lastMileTravelString: "3.0 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 22:30:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: "30% OFF",
                subHeader: "UPTO ₹75",
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/bombay-shiv-sagar-camac-street-kolkata-31623",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "384147",
            name: "Bake Me Good",
            cloudinaryImageId: "iyxvyevsufrqrojgsuss",
            locality: "Central Kolkata",
            areaName: "Bediadanga",
            costForTwo: "₹200 for two",
            cuisines: ["Bakery", "Snacks"],
            avgRating: 4.7,
            veg: true,
            parentId: "39945",
            avgRatingString: "4.7",
            totalRatingsString: "100+",
            sla: {
                deliveryTime: 28,
                lastMileTravel: 3.5,
                serviceability: "SERVICEABLE",
                slaString: "28 mins",
                lastMileTravelString: "3.5 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 20:30:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/bake-me-good-central-bediadanga-kolkata-384147",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
        info: {
            id: "103051",
            name: "The Rose",
            cloudinaryImageId: "165ae8bb0c6644977ac5a6e52ca973fc",
            locality: "CIT. Road, Kankurgachi",
            areaName: "Phoolbagan",
            costForTwo: "₹350 for two",
            cuisines: ["Chinese", "South Indian"],
            avgRating: 4.6,
            parentId: "1632",
            avgRatingString: "4.6",
            totalRatingsString: "1K+",
            sla: {
                deliveryTime: 33,
                lastMileTravel: 3.5,
                serviceability: "SERVICEABLE",
                slaString: "33 mins",
                lastMileTravelString: "3.5 km",
                iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
                nextCloseTime: "2023-12-27 22:00:00",
                opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: "seo-data-59e9a374-c122-456e-9f2f-5b7884f0de84",
        },
        cta: {
            link: "https://www.swiggy.com/restaurants/the-rose-cit-road-kankurgachi-phoolbagan-kolkata-103051",
            text: "RESTAURANT_MENU",
            type: "WEBLINK",
        },
        widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
];
